<?php

namespace Amicus\FilamentEmployeeManagement\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class PublishEmployeeReportTemplate extends Command
{
    protected $signature = 'employee-management:publish-template
                          {--force : Overwrite existing template}';

    protected $description = 'Publish employee report template to storage directory';

    public function handle(): int
    {
        $this->info('Employee Report Template Publisher');
        $this->newLine();

        // Show current configuration
        $this->showCurrentConfiguration();

        // Define paths
        $sourcePath = $this->getSourceTemplatePath();
        $targetPath = $this->getTargetTemplatePath();
        $configuredPath = storage_path(config('employee-management.monthly_report.template_path'));

        // Check if source template exists
        if (! File::exists($sourcePath)) {
            $this->error("Source template not found at: {$sourcePath}");
            $this->warn('The default template should be included with the package.');

            return self::FAILURE;
        }

        // Check if target already exists
        if (File::exists($targetPath) && ! $this->option('force')) {
            $this->warn("Template already exists at: {$targetPath}");
            $this->info('Use --force to overwrite the existing template.');
            $this->newLine();

            if (! $this->confirm('Do you want to overwrite the existing template?')) {
                $this->info('Template publishing cancelled.');

                return self::SUCCESS;
            }
        }

        // Create directory if it doesn't exist
        $targetDir = dirname($targetPath);
        if (! File::exists($targetDir)) {
            File::makeDirectory($targetDir, 0755, true);
            $this->info("Created directory: {$targetDir}");
        }

        // Copy template
        try {
            File::copy($sourcePath, $targetPath);
            $this->info("Template published successfully to: {$targetPath}");
            $this->newLine();

            // Show next steps
            $this->showNextSteps($targetPath, $configuredPath);

            return self::SUCCESS;
        } catch (\Exception $e) {
            $this->error("Failed to publish template: {$e->getMessage()}");

            return self::FAILURE;
        }
    }

    protected function showCurrentConfiguration(): void
    {
        $templatePath = config('employee-management.monthly_report.template_path');
        $autogeneratedEnabled = config('employee-management.monthly_report.enable_autogenerated', false);
        $fullPath = storage_path($templatePath);

        $this->table(
            ['Setting', 'Value'],
            [
                ['Template Path (config)', $templatePath],
                ['Full Storage Path', $fullPath],
                ['Template Exists', File::exists($fullPath) ? '✓ Yes' : '✗ No'],
                ['Autogenerated Enabled', $autogeneratedEnabled ? 'Yes' : 'No'],
            ]
        );

        $this->newLine();
    }

    protected function getSourceTemplatePath(): string
    {
        // Try multiple possible source locations
        $possiblePaths = [
            __DIR__ . '/../../../resources/templates/evidencija_radnog_vremena.xlsx',
            __DIR__ . '/../../../templates/evidencija_radnog_vremena.xlsx',
            storage_path('templates/evidencija_radnog_vremena.xlsx'),
        ];

        foreach ($possiblePaths as $path) {
            if (File::exists($path)) {
                return $path;
            }
        }

        // If not found, return the first expected location
        return $possiblePaths[0];
    }

    protected function getTargetTemplatePath(): string
    {
        return storage_path('templates/evidencija_radnog_vremena.xlsx');
    }

    protected function showNextSteps(string $publishedPath, string $configuredPath): void
    {
        $this->info('📋 Next Steps:');
        $this->newLine();

        $this->line('1. Customize your template:');
        $this->comment("   Edit: {$publishedPath}");
        $this->newLine();

        if ($publishedPath !== $configuredPath) {
            $this->line('2. Update your .env file to use the published template:');
            $relativePath = str_replace(storage_path('/') . '', '', $publishedPath);
            $this->comment("   EMPLOYEE_REPORT_TEMPLATE_PATH={$relativePath}");
            $this->newLine();
        }

        $this->line('3. Test the report export:');
        $this->comment('   - Navigate to an employee view page in Filament');
        $this->comment('   - Click "Mjesečni izvještaj radnih sati"');
        $this->comment('   - Select month/year and download');
        $this->newLine();

        $this->line('4. (Optional) Version control your template:');
        $this->comment("   git add {$publishedPath}");
        $this->comment('   git commit -m "Add custom employee report template"');
        $this->newLine();

        $this->info('For more information, see: docs/EMPLOYEE_REPORTS.md');
    }
}
