<?php

// config for Amicus/FilamentEmployeeManagement
return [
    'telegram-bot-api' => [
        'is_active' => false,
        'general_notification' => env('TELEGRAM_CHAT_ID', '-1003036762716'),
    ],

    'resources' => [
    ],

    'forms' => [
    ],

    'enabled_features' => [
        'tasks' => false,
        'projects' => false,
    ],

    /**
     * Employee monthly report template configuration
     *
     * Each inkubator can configure their own Excel template path and report options.
     * This allows customization of the monthly employee time reports per inkubator.
     *
     * @see docs/EMPLOYEE_REPORTS.md for detailed documentation
     */
    'monthly_report' => [
        /**
         * Path to the Excel template file (relative to storage path)
         *
         * Default: storage/templates/evidencija_radnog_vremena.xlsx
         *
         * To customize the template for your inkubator:
         * 1. Copy the default template to your desired location (e.g., storage/templates/my_inkubator_template.xlsx)
         * 2. Modify the template to match your inkubator's requirements
         * 3. Set EMPLOYEE_REPORT_TEMPLATE_PATH in your .env file:
         *    EMPLOYEE_REPORT_TEMPLATE_PATH=templates/my_inkubator_template.xlsx
         *
         * Template structure requirements:
         * - Must contain 12 sheets (one per month): Siječanj, Veljača, Ožujak, Travanj, Svibanj, Lipanj,
         *   Srpanj, Kolovoz, Rujan, Listopad, Studeni, Prosinac
         * - Each sheet must follow the expected cell layout for data population
         *
         * Note: The path is relative to the storage/ directory, not storage/app/
         */
        'template_path' => env('EMPLOYEE_REPORT_TEMPLATE_PATH', 'templates/evidencija_radnog_vremena.xlsx'),

        /**
         * Enable/disable the autogenerated Excel report option
         *
         * Default: false (disabled)
         *
         * When set to false (default):
         * - Users will only see the template-based export option
         * - The template selector field is hidden from the UI
         * - All reports use the Excel template defined in 'template_path'
         *
         * When set to true:
         * - Users can choose between:
         *   1. "Generirani Excel izvještaj" - Simple autogenerated Excel from scratch
         *   2. "Službeni predložak" - Uses the configured Excel template
         * - A dropdown selector appears in the UI to choose the report type
         *
         * To enable autogenerated reports, set in your .env file:
         * EMPLOYEE_REPORT_ENABLE_AUTOGENERATED=true
         *
         * Recommendation: Keep disabled unless you specifically need the autogenerated option,
         * as template-based reports provide better formatting and consistency.
         */
        'enable_autogenerated' => env('EMPLOYEE_REPORT_ENABLE_AUTOGENERATED', false),
    ],
];
